version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=storeweb_user
      - POSTGRES_PASSWORD=storeweb_password
      - POSTGRES_DB=storeweb_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: runtime
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=storeweb_user
      - POSTGRES_PASSWORD=storeweb_password
      - POSTGRES_DB=storeweb_db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
        - ./frontend:/app
        - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  postgres_data:
