"""Consolidate Coupon models

Revision ID: 192eb5c0ee5f
Revises: df5228d67d1e
Create Date: 2026-02-19 05:37:46.263022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '192eb5c0ee5f'
down_revision: Union[str, Sequence[str], None] = 'df5228d67d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_id'), table_name='coupons')
    op.drop_table('coupons')
    op.add_column('store_coupons', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('store_coupons', sa.Column('discount_percent', sa.Float(), nullable=False))
    op.add_column('store_coupons', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('store_coupons', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('store_coupons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_store_coupons_code'), 'store_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_store_coupons_id'), 'store_coupons', ['id'], unique=False)
    op.drop_column('store_coupons', 'usage_limit')
    op.drop_column('store_coupons', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_coupons', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('store_coupons', sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_store_coupons_id'), table_name='store_coupons')
    op.drop_index(op.f('ix_store_coupons_code'), table_name='store_coupons')
    op.drop_column('store_coupons', 'created_at')
    op.drop_column('store_coupons', 'expires_at')
    op.drop_column('store_coupons', 'max_uses')
    op.drop_column('store_coupons', 'discount_percent')
    op.drop_column('store_coupons', 'id')
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_uses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('coupons_pkey'))
    )
    op.create_index(op.f('ix_coupons_id'), 'coupons', ['id'], unique=False)
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    # ### end Alembic commands ###
