"""Add delivery_key

Revision ID: 7b37ee859158
Revises: 1e7bb5716fd8
Create Date: 2026-02-20 10:35:57.306486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b37ee859158'
down_revision: Union[str, Sequence[str], None] = '1e7bb5716fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_orders', sa.Column('delivery_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_orders', 'delivery_key')
    # ### end Alembic commands ###
