"""Add attachment_url to messages

Revision ID: 857dcc22b512
Revises: 338f8f93f1cc
Create Date: 2026-02-19 05:00:24.074496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857dcc22b512'
down_revision: Union[str, Sequence[str], None] = '338f8f93f1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_order_messages', sa.Column('attachment_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_order_messages', 'attachment_url')
    # ### end Alembic commands ###
