"""Add order_id to reviews

Revision ID: ca53031120f3
Revises: 7b37ee859158
Create Date: 2026-02-20 09:28:53.533020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca53031120f3'
down_revision: Union[str, Sequence[str], None] = '7b37ee859158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_reviews', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_store_reviews_order_id'), 'store_reviews', ['order_id'], unique=False)
    op.create_foreign_key(None, 'store_reviews', 'store_orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_store_reviews_order_id'), table_name='store_reviews')
    op.drop_column('store_reviews', 'order_id')
    # ### end Alembic commands ###
