"""Add read_at to messages

Revision ID: f5c834cbdd2d
Revises: 028b778dd4b1
Create Date: 2026-02-19 05:23:12.262445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c834cbdd2d'
down_revision: Union[str, Sequence[str], None] = '028b778dd4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_order_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('store_ticket_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_ticket_messages', 'read_at')
    op.drop_column('store_order_messages', 'read_at')
    # ### end Alembic commands ###
