apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storeweb-ingress
  namespace: storeweb
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: storeweb.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: storeweb-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storeweb-frontend
                port:
                  number: 5173
  tls:
    - hosts:
        - storeweb.example.com
      secretName: storeweb-tls-secret